package io.dd.test.core;

public enum ProcessStatus {
    CREATED,
    BUDGET_ALLOCATED,
    BUDGET_FAILED,
    BUDGET_ALLOCATION_CANCELED,
    RESOURCES_PASSED,
    RESOURCES_FAILED,
    RESOURCES_CANCELED,
    APPROVED,
    REJECTED,
    ILLEGAL_STATE
}
